modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="create_utilities"
version="0.3.1"
displayName="Create Utilities"
authors="Kura, Duquee"
description='''
Adds Create-compatible void storage and utility blocks. This is a version ported to 1.21.1.
'''

[[dependencies.create_utilities]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_utilities]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1, 1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_utilities]]
    modId="create"
    type="required"
    versionRange="[6.0.4,)"
    ordering="AFTER"
    side="BOTH"